# Generated by Django 5.2.4 on 2025-08-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'Assignment'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Match'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Team'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'verbose_name_plural': 'Training Session'},
        ),
    ]
