# Generated by Django 5.2.4 on 2025-08-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0002_alter_assignment_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('New', 'New'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Broken', 'Broken'), ('Repaired', 'Repaired')], default='Good', max_length=50),
        ),
    ]
