# Generated by Django 5.2.4 on 2025-08-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0005_role_alter_match_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
